name: Basic CI

on: pull_request

env:
    NODE_VERSION: 20.x

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Environment ( ${{ env.NODE_VERSION }} )
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install dependencies
              run: npm ci

            - name: Build package
              run: npm run build

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Environment ( ${{ env.NODE_VERSION }} )
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install dependencies
              run: npm ci

            - run: npm run lint
